config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root 'root#index'
  get '/about', to:"root#about", as:"about"
  get '/my_jobs', to:"my_jobs#index"
  post '/save_job/:id', to: 'root#save_job', as:"save_job"
  post '/remove_job/:id', to: 'root#remove_job', as:"remove_job"
  get '/post/:id', to:"root#view_post", as:"view_post"
  delete '/remove_history_item/:id', to: 'root#remove_history_item'
  get '/company/:company_slug', to: 'root#view_company', as: "view_company"
  get '/settings', to:"users#settings", as:"user_settings"
  patch '/update_settings', to:"users#update_settings", as:"update_user_settings"

  resources :resumes do
    member do
      get :download_json
    end
    collection do
      get :new_category
      get :preview
      post :preview
    end
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint(8)        not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :saved_jobs
  has_many :job_postings, through: :saved_jobs
  has_many :resumes
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:settings, :update_settings]

  def settings
  end

  def update_settings
    respond_to do |format|
      if @user.update(user_params)
        bypass_sign_in(@user)
        format.html { redirect_to user_settings_path, notice: 'Update Successful!' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

private
  def set_user
    @user = current_user
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
    params.require(:user).permit(:first_name, :last_name, :address, :city, :state, :zip, :phone_number, :website, :password, :password_confirmation)
  end
end

app/views/users/_form.html.erb
<div class='container'>
  <div class="row">
    <div class="col-sm-12">
      <div class="panel panel-default">
        <div class="panel-heading"><h3 class="panel-title">Settings</h3></div>
        <div class="panel-body">
          <%= form_for(user, url: update_user_settings_path, html: { class:'form-horizontal', role:'form' }) do |f| %>
          <% if user.errors.any? %>
            <div class="alert alert-danger" id="error_explanation">
              <strong><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</strong>
              <ul>
                <% user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class="form-group">
            <%= f.label :first_name, class:'col-md-2 control-label' %>
            <div class="col-md-10">
              <%= f.text_field :first_name, class:'form-control' %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :last_name, class:'col-md-2 control-label' %>
            <div class="col-md-10">
              <%= f.text_field :last_name, class:'form-control' %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :address, class:'col-md-2 control-label' %>
            <div class="col-md-10">
              <%= f.text_field :address, class:'form-control' %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :city, class:'col-md-2 control-label' %>
            <div class="col-md-10">
              <%= f.text_field :city, class:'form-control', autocomplete:"off" %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :state, class:'col-md-2 control-label' %>
            <div class="col-md-10">
              <%= f.text_field :state, class:'form-control', autocomplete:"off" %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :zip, class:'col-md-2 control-label' %>
            <div class="col-md-10">
              <%= f.number_field :zip, class:'form-control', autocomplete:"off" %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :phone_number, class:'col-md-2 control-label' %>
            <div class="col-md-10">
              <%= f.text_field :phone_number, class:'form-control', autocomplete:"off" %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :website, class:'col-md-2 control-label' %>
            <div class="col-md-10">
              <%= f.text_field :website, class:'form-control', autocomplete:"off" %>
            </div>
          </div>
          <% unless params[:action] == "new" || params[:action] == "create" %>
            <div class="form-group">
              <%= f.label :password, class:'col-md-2 control-label' %>
              <div class="col-md-10">
                <%= f.password_field :password, class:'form-control', autocomplete:"off"  %>
              </div>
            </div>
            <div class="form-group">
              <%= f.label "Password Confirmation", class:'col-md-2 control-label' %>
              <div class="col-md-10">
                <%= f.password_field :password_confirmation, class:'form-control', autocomplete:"off"  %>
              </div>
            </div>
          <% end %>
          <div class="form-group m-b-0">
            <div class="col-sm-offset-2 col-sm-9">
              <%= f.submit "Update Settings", class:'btn btn-primary' %>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/settings.html.erb
<div class="row">
  <div class="col-lg-12">
    <%= render 'form', user: @user %>
  </div>
</div>