config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root 'root#index'
  get '/about', to:"root#about", as:"about"
  get '/my_jobs', to:"my_jobs#index"
  post '/save_job/:id', to: 'root#save_job', as:"save_job"
  post '/remove_job/:id', to: 'root#remove_job', as:"remove_job"
  get '/post/:id', to:"root#view_post", as:"view_post"
  delete '/remove_history_item/:id', to: 'root#remove_history_item'
  get '/company/:company_slug', to: 'root#view_company', as: "view_company"
  get '/settings', to:"users#settings", as:"user_settings"
  patch '/update_settings', to:"users#update_settings", as:"update_user_settings"

  resources :resumes do
    member do
      get :download_json
    end
    collection do
      get :new_category
      get :preview
      post :preview
    end
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  before_action :authenticate_user!, only: [:save_job, :remove_job]

  def index
    load_jobs

    respond_to do |format|
      format.html
      format.js
      format.rss { render layout: false }
      format.json { render json: JSONAPI::Serializer.serialize(@job_postings, is_collection: true) }
    end
  end

  def about
  end

  def view_post
    @posting = JobPosting.find(params[:id])
    respond_to do |format|
      format.html do
        history_item = {id: @posting.id, title: @posting.title}
        session[:viewed_post_history] ||= []
        # preventing duplicates; todo: might be good to move duplicate to the front instead of just ignoring?
        unless session[:viewed_post_history].any? {|h| h["id"] == @posting.id}
          session[:viewed_post_history].unshift(history_item)
        end
      end
      format.json { render json: JSONAPI::Serializer.serialize(@posting) }
      format.rss { render layout: false }
    end
  end

  def view_company
    @job_postings = JobPosting.
      where(company_slug: params[:company_slug]).
      paginate(page: params[:page]).
      order("publish_date desc")
    
    respond_to do |format|
      format.html
      format.json { render json: JSONAPI::Serializer.serialize(@job_postings, is_collection: true) }
      format.rss { render layout: false }
    end
  end

  def save_job
    job_posting = JobPosting.find_by(id: params[:id])
    saved_job = SavedJob.new(user_id: current_user.id, job_posting_id: job_posting.id)
    if saved_job.save
      flash[:notice] = "Job Was Successfully Saved!"
    else
      flash[:alert] = saved_job.errors.full_messages.join(',')
    end

    redirect_to root_path
  end

  def remove_job
    current_user.saved_jobs.find_by(job_posting_id: params[:id]).destroy
    flash[:notice] = "Job Was Successfully Removed!"

    redirect_back(fallback_location: root_path)
  end

  def remove_history_item
    @item = session[:viewed_post_history].detect { |e| e['id'] == params[:id].to_i }
    session[:viewed_post_history].delete(@item)

    respond_to do |format|
      @empty_history_items = session[:viewed_post_history].empty?
      format.js
    end
  end

  private

  def load_jobs
    @job_postings = params[:query].blank? ?
                    JobPosting.paginate(page: params[:page]).order("publish_date desc") :  
                    JobPosting.search_by_title(params[:query]).paginate(page: params[:page]).reorder("publish_date desc")
  end
end

app/views/root/_job_postings.html.erb
<div class="job_posts">
  <% job_postings.each do |posting| %>
    <div class="media">
      <div class="media-left">
        <% if posting.logo.blank? %>
          <div class="card-img-top color-box" style="background:#<%= posting.random_color %>;"><%= posting.company_initials %></div>
        <% else %>
          <img class="card-img-top" src="<%= posting.logo %>" alt="Card image cap">
        <% end %>
      </div>
      <div class="media-body">
        <div class="col-md-12">
          <h4 class="media-heading ">
            <%= link_to posting.title, view_post_path(posting) %>
            <br>
            <small>
              <%= link_to posting.company, view_company_path(company_slug: posting.company_slug) %> | <%= local_time(posting.publish_date, '%B %e, %Y') %> | <%= link_to "View Post On #{posting.job_board}", posting.url, target:"_blank" %>
            </small>
          </h4>
          
          <%= truncate(posting.description_formatted, length: 300) %>
          <div class="save-job-action">
           <% if current_user %>
            <% if current_user.job_postings.include?(posting) %>
              <%= link_to 'Remove Job', remove_job_path(posting.id), remote: true, method: :post, class: 'btn btn-custom-remove', id: posting.id %>
            <% else %>
              <%= link_to 'Save Job', save_job_path(posting.id), remote: true, method: :post, class: 'btn btn-primary', id: posting.id %>
            <% end %>
          <% end %>
          </div>
        </div>
      </div>
    </div>
    <hr />
  <% end %>
</div>

app/views/root/about.html.erb
<section>
  <div class="container">

  <div class="row align-items-center justify-content-center">
    <div class="col-md-4">
      <div class="page-header">
        <%= image_tag('about.jpg', class:'img-rounded img-fluid') %>
        <br>
      </div>
    </div>
    <div class="col-md-8">

      <%= image_tag('logo.png') %>
      <hr>
      <h1>Welcome to Jobby Job Job!</h1>
      <p>
        My name is Will Wilimek. I created this site to
        aggregate remote developer jobs so I wouldn't have to use 4 different job
        boards when I'm looking for interesting jobs or projects. I also wanted
        to help people find job and use this project as an example of my experience
        working with Ruby/Rails since most of my code is owned by a company and
        can't be released.
      </p>
      
      <p>
         The site is currently hosted on heroku (free). It uses a postgres backend database and
          a scheduler job to populate jobs every hour from various job boards.
      </p>
     
      <p>
        If you want to check out more about me you can find my blog at <%= link_to 'wosnet.net', 'https://www.wosnet.net/' %>
      </p>
      
      <p>
        If you want to hack on this project with me you can check it out on <%= link_to 'GitHub.', 'https://github.com/willywos/jobbyjobjob' %> Pull requests welcome!
      </p>
      
      <p>
        <== This is me and my kids on vacation!
      </p>
      
      <p>
        Feel free to reach out if you have a feature or bug or just wanna work on this or wanna know how something here works. <%= link_to 'Contact Me', 'mailto:wwilimek@gmail.com' %>
      </p>
      
      <br><br>
      
    </div>
  </div>
</div>
</section>

app/views/root/index.html.erb
<%= content_for :head do %>
  <link rel="alternate" type="application/rss+xml" title="Subscribe to Jobby Job Job Feeds" href="<%= root_url(query: params[:query], page: params[:page], format: :rss) %>" />
<% end %>
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <div class="page-header">
        <%= image_tag('hero.png', class:'img-rounded img-responsive') %>
        <h4>Search for remote programming jobs across multiple job boards!</h4>
        <%= image_tag('companies.png', class:'img-responsive') %>
        <br>
      </div>
      <div class="job_pagination add_remote">
        <%= will_paginate @job_postings, params: {query: params[:query]} %>
      </div>
      <%= render partial:"root/job_postings", locals: { job_postings: @job_postings } %>
      <div class="job_pagination add_remote">
        <%= will_paginate @job_postings, params: {query: params[:query]} %>
      </div>
    </div>
    <div class="col-md-4 side_info">
      <div class="filtering_container hidden visible-md visible-lg">
        <div class="card ">
          <h5 class="card-header">Search</h5>
          <div class="card-body">

              <%= form_with url: root_path, id:'searchForm', class:'form-inline', method: :get do |form| %>
                <div class='form-group'>
                  <div class="input-group">
                    <%= form.text_field :query, class:'form-control', placeholder:'Search for...' %>
                  </div>
                </div>
                  <%= form.submit "Go!", class:"btn btn-primary" %>
                <% end %>
            </div>
        </div>
        <div class="card ">
          <h5 class="card-header">Quick Search</h5>
          <div class="card-body">
            <div class="row">
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <li>
                    <a href="javascript:populateSearch('node')">Node</a>
                  </li>
                  <li>
                    <a href="javascript:populateSearch('javascript')">JavaScript</a>
                  </li>
                  <li>
                    <a href="javascript:populateSearch('react')">React</a>
                  </li>
                  <li>
                    <a href="javascript:populateSearch('java')">Java</a>
                  </li>
                  <li>
                    <a href="javascript:populateSearch('ruby')">Ruby</a>
                  </li>
                  <li>
                    <a href="javascript:populateSearch('rails')">Rails</a>
                  </li>
                  <li>
                    <a href="javascript:populateSearch('go')">Go</a>
                  </li>
                  <li>
                    <a href="javascript:populateSearch('sql')">SQL</a>
                  </li>
                  <li>
                    <a href="javascript:populateSearch('devops')">DevOps</a>
                  </li>
                  <li>
                    <a href="javascript:populateSearch('full stack')">Full Stack</a>
                  </li>
                  <li>
                    <a href="javascript:populateSearch('front end')">Front End</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
      <%= link_to "javascript: toggleFilter();", class: "visible-xs visible-sm toggle_button btn btn-primary" do %>
        <i class="glyphicon glyphicon-search"></i>
      <% end %>
      <div class="card ">
        <h5 class="card-header">Jobby Job Job Status</h5>
        <div class="card-body">
          <strong>Last Refresh:</strong> <br>
          <% if JobPosting.last %>
              <%= local_time(JobPosting.last.created_at, format: '%B %e, %Y %l:%M%P') %>
          <% else %>
              <%= local_time(DateTime.now, format: '%B %e, %Y %l:%M%P') %>
          <% end %>
          <br><br>
          <strong>Total Number Of Jobs:</strong><br> <%= JobPosting.all.count %>
          <br><br>
          <%= content_tag :div, id: 'history-items-list' do %>
            <strong>Your View History:</strong>
            <ul class="list-unstyled mb-0">
              <% session[:viewed_post_history].each do |history| %>
                <li class="history-item" data-item-id="<%= history["id"] %>">
                  <%= link_to history["title"], "/post/" + history["id"].to_s, target: "_blank" %>
                  <%= link_to "", "/remove_history_item/" + history["id"].to_s, method: :delete, remote: true, class: 'fas fa-trash' %>
                </li>
              <% end %>
            </ul>
          <% end if session[:viewed_post_history] != nil && session[:viewed_post_history].length > 0 %>
          <strong>Subscribe & Share</strong> <br>
          <%= link_to "", root_url(page: params[:page], query: params[:query], format: :rss), class: "fas fa-rss" %>
          <%= link_to "{json.api}", root_url(page: params[:page], query: params[:query], format: :json) %>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/root/index.js.erb
$(".job_posts").html("<%= escape_javascript(render(:partial => 'root/job_postings', locals: { job_postings: @job_postings })) %>");
$(".job_pagination").html("<%= escape_javascript( will_paginate @job_postings ) %>");
$('.job_pagination.add_remote a').attr('data-remote', 'true');

app/views/root/remove_history_item.js.erb
$(".history-item[data-item-id=<%= @item["id"] %>]").remove()

<% if @empty_history_items %>
    $("#history-items-list").remove()
<% end %>

app/views/root/remove_job.js.erb
$("#<%= params[:id] %>").removeClass("btn-custom-remove").addClass("btn-primary").text("Save Job").attr("href", "/save_job/<%= params[:id] %>")

app/views/root/save_job.js.erb
$("#<%= params[:id] %>").addClass("btn-custom-remove").removeClass("btn-primary").text("Remove Job").attr("href", "/remove_job/<%= params[:id] %>")

app/views/root/view_company.html.erb
<%= content_for :head do %>
  <link rel="alternate" type="application/rss+xml" title="Subscribe to Jobby Job Job Feeds" href="<%= view_company_url(company_slug: params[:company_slug], format: :rss) %>" />
<% end %>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="company_post">
        <div class="media">
          <div class="media-left">
            <% if @job_postings.first.logo.blank? %>
              <div class="card-img-top color-box" style="background:#<%= @job_postings.first.random_color %>;"><%= @job_postings.first.company_initials %></div>
            <% else %>
              <img class="card-img-top" src="<%= @job_postings.first.logo %>" alt="Card image cap">
            <% end %>
          </div>
          <div class="media-body">

            <div class="pull-right">
              <%= link_to 'Back', 'javascript:window.history.back()', class:'btn btn-primary' %>
            </div>

            <h4>
              <%= @job_postings.first.company %>
            </h4>

          </div>
        </div>

        <hr>

        <%= render partial:"root/job_postings", locals: { job_postings: @job_postings } %>
        <div class="job_pagination add_remote">
          <%= will_paginate @job_postings %>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/root/view_post.html.erb
<%= content_for :head do %>
  <link rel="alternate" type="application/rss+xml" title="Subscribe to Jobby Job Job Feeds" href="<%= view_post_url(@posting, format: :rss) %>" />
<% end %>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="job_posts">

          <div class="media">
            <div class="media-left">
              <% if @posting.logo.blank? %>
                <div class="card-img-top color-box" style="background:#<%= @posting.random_color %>;"><%= @posting.company_initials %></div>
              <% else %>
                <img class="card-img-top" src="<%= @posting.logo %>" alt="Card image cap">
              <% end %>
            </div>
            <div class="media-body">
              <div class="pull-right"><%= link_to 'Back', 'javascript:window.history.back()', class:'btn btn-primary' %></div>
              <h4 class="media-heading"><%= link_to @posting.title, @posting.url, target:"_blank" %> <br><small><%= link_to @posting.company, view_company_path(company_slug: @posting.company_slug) %> | <%= local_time(@posting.publish_date, '%B %e, %Y') %></small></h4>
              <hr>
              <div class="post-card">
                <div class="post-card-content">
                  <style type="text/css">
                    ul br {
                      display: none;
                    }
                    p {
                      margin-top: 0;
                      margin-bottom: 1em;
                    }

                  </style>
                  <span id="posting">
                  <%= auto_link(@posting.description_formatted_for_post.html_safe) %>
                  </span>
                </div>
                <div class="post-card-details">
                  <div class="center">
                    <%= link_to 'View Original Job Post', @posting.url, target:"_blank", class:'btn btn-primary' %>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <hr>
      </div>
    </div>
  </div>
</div>