config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root 'root#index'
  get '/about', to:"root#about", as:"about"
  get '/my_jobs', to:"my_jobs#index"
  post '/save_job/:id', to: 'root#save_job', as:"save_job"
  post '/remove_job/:id', to: 'root#remove_job', as:"remove_job"
  get '/post/:id', to:"root#view_post", as:"view_post"
  delete '/remove_history_item/:id', to: 'root#remove_history_item'
  get '/company/:company_slug', to: 'root#view_company', as: "view_company"
  get '/settings', to:"users#settings", as:"user_settings"
  patch '/update_settings', to:"users#update_settings", as:"update_user_settings"

  resources :resumes do
    member do
      get :download_json
    end
    collection do
      get :new_category
      get :preview
      post :preview
    end
  end
end

app/models/resume.rb
class Resume < ApplicationRecord
  belongs_to :user
  serialize :data

  DEFAULT_DATA_TEMPLATE = {
    "basics": {
      "name": "",
      "label": "",
      "picture": "",
      "email": "",
      "phone": "",
      "website": "",
      "summary": "",
      "location": {
        "address": "",
        "postalCode": "",
        "city": "",
        "countryCode": "",
        "region": ""
      },
      "profiles": []
    },
    "work": [],
    "volunteer": [],
    "education": [],
    "awards": [],
    "publications": [],
    "skills": [],
    "languages": [],
    "interests": [],
    "references": []
  }

  PROFILES_TEMPLATE = {
    "network": "",
    "username": "",
    "url": ""
  }

  WORK_TEMPLATE = {
    "company": "",
    "position": "",
    "website": "",
    "startDate": "",
    "endDate": "",
    "summary": "",
    "highlights": []
  }

  VOLUNTEER_TEMPLATE = {
    "organization": "",
    "position": "",
    "website": "",
    "startDate": "",
    "endDate": "",
    "summary": "",
    "highlights": []
  }

  EDUCATION_TEMPLATE = {
    "institution": "",
    "area": "",
    "studyType": "",
    "startDate": "",
    "endDate": "",
    "gpa": "",
    "courses": []
  }

  AWARDS_TEMPLATE = {
    "title": "",
    "date": "",
    "awarder": "",
    "summary": ""
  }

  PUBLICATIONS_TEMPLATE = {
    "name": "",
    "publisher": "",
    "releaseDate": "",
    "website": "",
    "summary": ""
  }

  SKILLS_TEMPLATE = {
    "name": "",
    "level": "",
    "keywords": []
  }

  LANGUAGES_TEMPLATE = {
    "language": "",
    "fluency": ""
  }

  INTERESTS_TEMPLATE = {
    "name": "",
    "keywords": []
  }

  REFERENCES_TEMPLATE = {
    "name": "",
    "reference": ""
  }
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :authenticate_user!
  before_action :load_resume, only: [:edit, :update, :destroy, :download_json]
  skip_before_action :verify_authenticity_token, :only => [:preview] # turbolinks issue solver

  def index
    @resumes = current_user.resumes
  end

  def new
    @resume = Resume.new(user_id: current_user.id)
  end

  def create
    @resume = Resume.new(resume_params)
    if @resume.save
      redirect_to resumes_path and return
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @resume.update_attributes(resume_params)
      redirect_to resumes_path and return
    else
      render :edit
    end
  end

  def destroy
    @resume.delete
  end

  def preview
    @json_data = (params[:resume].try(:[], :data) || {}).to_json
    render :preview, layout: "document"
  end

  def download_json
    send_data (@resume.data || {}).to_json, :type => 'application/json; header=present', :disposition => "attachment; filename=#{@resume.name}.json"
  end

  private

  def load_resume
    @resume = current_user_resume(params[:id])
    redirect_to resumes_path and return if @resume.blank?
  end

  def current_user_resume(id)
    current_user.resumes.where(id: id).first
  end

  def resume_params
    new_params = params.require(:resume).permit(:name, :user_id, data: {})
    new_params[:resume][:data] = new_params[:resume][:data].to_h if new_params[:resume].try(:[], :data).present?
    new_params
  end
end

app/helpers/resumes_helper.rb
module ResumesHelper

  def check_value(resume_data, array_of_fields)
    tmp_data = resume_data
    array_of_fields.each do |f|
      tmp_data = tmp_data.try(:[], f) || ''
      break if tmp_data.class == String
    end
    return tmp_data
  end
end

app/views/resumes/_category.html.erb
<div class="category <%= category %>">
  <h3>
    <%= category.titleize %>
  </h3>

  <div class="actual_data">
    <%= render partial: ('resumes/categories/category_template'), locals: {data_to_parse: @resume.data.try(:[], category), category: category} %>
  </div>
  <%= link_to "Add", new_category_resumes_path(category_target: category), class: "btn btn-sm btn-default", remote: true %>
  <%= link_to "Remove", "javascript: removeClosestObject('#{category}');", class: "btn btn-sm btn-default" %>
</div>

app/views/resumes/_form.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-4">
    <%= form_for @resume, html: {class: "resume_form"} do |f| %>
      <%= f.hidden_field :user_id %>
      <%= f.label :name, "Resume Name" %>
      <%= f.text_field :name, limit: 255, class: "form-control" %>

      <hr/>

      <%= f.fields_for "data[basics]" do |ff| %>
        <% Resume::DEFAULT_DATA_TEMPLATE[:basics].each do |key, value| %>
          <% if value.class == String %>
            <%= ff.label key %>
            <%= ff.text_field key, value: check_value(@resume.data, ["basics", key.to_s]), class: "form-control" %>
            <br/>
          <% end %>
        <% end %>
        <!-- location -->
        <%= ff.fields_for "location" do |fff| %>
          <% Resume::DEFAULT_DATA_TEMPLATE[:basics][:location].each do |key, value| %>
            <% if value.class == String %>
              <%= fff.label key %>
              <%= fff.text_field key, value: check_value(@resume.data, ["basics", "location", key.to_s]), class: "form-control" %>
            <% end %>
            <br/>
          <% end %>
        <% end %>
      <% end %>

      <%= render partial: "resumes/category", locals: {category: "profiles"} %>
      <%= render partial: "resumes/category", locals: {category: "work"} %>
      <%= render partial: "resumes/category", locals: {category: "volunteer"} %>
      <%= render partial: "resumes/category", locals: {category: "education"} %>
      <%= render partial: "resumes/category", locals: {category: "awards"} %>
      <%= render partial: "resumes/category", locals: {category: "skills"} %>
      <%= render partial: "resumes/category", locals: {category: "languages"} %>
      <%= render partial: "resumes/category", locals: {category: "interests"} %>
      <%= render partial: "resumes/category", locals: {category: "references"} %>

      <br/>

      <%= f.submit :save, class: "btn btn-primary" %>
    <% end %>
  </div>

  <div class="col-xs-12 col-sm-12 col-md-8" >
    <iframe name="preview" style="width: 100%; height: 600px;" data-target="preview" data-action="<%= preview_resumes_path %>" >

    </iframe>
  </div>
</div>

<%= javascript_tag do %>
  initForm();
<% end %>

app/views/resumes/_resume.html.erb
<tr id="resume_<%= resume.id %>">
  <td>
    <%= resume.name %>
  </td>
  <td>
    <%= local_time(resume.created_at, format: '%B %e, %Y %l:%M%P') %>
  </td>
  <td>
    <%= link_to edit_resume_path(resume) do %>
      <i class="glyphicon glyphicon-edit"></i>
    <% end %>

    <%= link_to download_json_resume_path(resume), class: "padding-left-5" do %>
      <i class="glyphicon glyphicon-download-alt"></i>
    <% end %>

    <%= link_to resume_path(resume), method: :delete, remote: true, data: {confirm: "Are you sure you want to delete?"}, class: "padding-left-5" do %>
      <i class="glyphicon glyphicon-trash"></i>
    <% end %>
  </td>
</tr>

app/views/resumes/destroy.js.erb
<% if @resume.destroyed? %>
  $("#resume_<%= @resume.id %>").remove();
<% end %>

app/views/resumes/edit.html.erb
<div class='container'>
  <%= render partial: "resumes/form" %>
</div>

app/views/resumes/index.html.erb
<div class='container'>
  <div class="row">
    <div class="col-xs-8">
      <h1>My resumes</h1>
    </div>
    <div class="col-xs-4">
      <h1>
        <%= link_to 'New Resume', new_resume_path, class: 'btn btn-primary pull-right' %>
      </h1>
    </div>
  </div>

  <hr />
  <% if @resumes.any? %>
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Created at</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <%= render @resumes %>
      </tbody>
    </table>

  <% else %>
    <h3>No resumes yet</h3>
  <% end %>
</div>

app/views/resumes/new.html.erb
<div class='container'>
  <%= render partial: "resumes/form" %>
</div>

app/views/resumes/new_category.js.erb
<% target = params[:category_target] %>
<% minor_target = params[:minor_object_target] %>
<% random_index = params[:random_index] %>
<% if minor_target.nil? %>
  $(".category.<%= target %> .actual_data").append("<%= j render partial: ('resumes/categories/category_template'), locals: {category: target} %>");
<% else %>
  $(".category.<%= target %> .actual_data .object_data.<%= random_index %> .minor_actual_data").append("<%= j render partial: 'resumes/categories/minor_object_template', locals: {category: target, key: minor_target, value: ''} %>");
<% end %>

app/views/resumes/preview.html.erb
<% content_for :boilerplate_tmp do %>
  <script src="/assets/hbs_files/boilerplate.hbs" type="text/x-handlebars-template"></script>
<% end %>

<%= javascript_tag do %>
  $(document).ready(function() {
      $(document).autoBars(function() {
        json = JSON.parse("<%== j @json_data %>");
        var data = { "resume" : json};
        var $html = $.handlebarTemplates['boilerplate'](data);
        $('body').append($html);
      });
    })
<% end %>