config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root 'root#index'
  get '/about', to:"root#about", as:"about"
  get '/my_jobs', to:"my_jobs#index"
  post '/save_job/:id', to: 'root#save_job', as:"save_job"
  post '/remove_job/:id', to: 'root#remove_job', as:"remove_job"
  get '/post/:id', to:"root#view_post", as:"view_post"
  delete '/remove_history_item/:id', to: 'root#remove_history_item'
  get '/company/:company_slug', to: 'root#view_company', as: "view_company"
  get '/settings', to:"users#settings", as:"user_settings"
  patch '/update_settings', to:"users#update_settings", as:"update_user_settings"

  resources :resumes do
    member do
      get :download_json
    end
    collection do
      get :new_category
      get :preview
      post :preview
    end
  end
end

app/views/layouts/_flash.html.erb
<div class='flash-container'>
  <% flash.each do |type, message| %>
    <div class="flash <%= type %>"><%= message %></div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="py-5 bg-dark">
    <p class="m-0 text-center text-white">Copyright &copy; Jobby Job Job <%= Date.current.year %></p>
</footer>

app/views/layouts/_navigation.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid" id="navfluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigationbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class:"navbar-brand" do %>
        <%= image_tag('logo.png', class:'img-responsive') %>
      <% end %>
    </div>
     <div class="collapse navbar-collapse" id='navigationbar'>
        <ul class="nav navbar-nav">
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'About', about_path %></li>
          <% if current_user %>
            <li><%= link_to 'My Jobs', my_jobs_path %></li>
            <li><%= link_to 'My Resumes', resumes_path %></li>
            <li><%= link_to 'Settings', user_settings_path  %></li>
            <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to 'Login', new_user_session_path %></li>
          <% end %>
        </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <title>Jobby Job Job</title>
    <meta name="description" content="Search for remote programming jobs across multiple job boards!" />
    <meta name="keywords" content="seach remote jobs, remote job, remote, jobs, job postings, remote postings, programming, developer jobs, programming jobs" />
    <meta name="author" content="willywos" />
    <meta name="robots" content="index, follow" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= yield :head %>
  </head>

  <body class="<%= params[:controller] %>">
    <%= render "layouts/navigation" %>
    <%= render 'layouts/flash' %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/layouts/document.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Jobby Job Job</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'document', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield :boilerplate_tmp %>
  </head>

  <body class="<%= params[:controller] %>">
    <%= yield %>
  </body>
</html>